In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'
dados = pd.read_csv(url)

In [3]:
dados.head(7)

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True
5  Bruna     23    NaN     False
6   Dara     21    7.0      True

In [4]:
dados.tail()

      Nome  Idade  Notas  Aprovado
13   Mirla     25    9.0      True
14   Paulo     37    NaN     False
15  Mylena     29    7.0      True
16   Lucas     33    NaN     False
17   Nadia     34    8.0      True

In [5]:
dados.shape

(18, 4)

In [6]:
dados.columns

Index(['Nome', 'Idade', 'Notas', 'Aprovado'], dtype='object')

In [7]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nome      18 non-null     object
 1   Idade     18 non-null     int64
 2   Notas     12 non-null     float64
 3   Aprovado  18 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 582.0+ bytes

In [8]:
#selecionando uma coluna
dados['Nome']

0           Ary
1           Ana
2         Cátia
3         Denis
4          Beto
5         Bruna
6          Dara
7        Carlos
8         Alice
9         Vitor
10       Daniel
11         Igor
12    Sthefanie
13        Mirla
14        Paulo
15       Mylena
16        Lucas
17        Nadia
Name: Nome, dtype: object

In [9]:
#selecionando múltiplas colunas
dados[['Idade', 'Notas']]

    Idade  Notas
0      20    7.5
1      18    NaN
2      27    2.5
3      18    5.0
4      21   10.0
5      23    NaN
6      21    7.0
7      19    6.0
8      35    5.6
9      28    NaN
10     21    NaN
11     24    4.5
12     26    9.5
13     25    9.0
14     37    NaN
15     29    7.0
16     33    NaN
17     34    8.0

In [10]:
# conferindo os tipos de dados de cada coluna
dados.dtypes

Nome         object
Idade         int64
Notas       float64
Aprovado       bool
dtype: object

In [11]:
dados.describe()

           Idade      Notas
count  18.000000  12.000000
mean   25.500000   6.800000
std     6.070662   2.204953
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000

1) Verifique se a base de dados possui dados nulos e, caso tenha, realize o tratamento desses dados nulos da forma que achar mais coerente com a situação.

2) Os alunos "Alice" e "Carlos", não fazem mais parte da turma. Sendo assim, remova-os da base de dados.

3) Aplique um filtro que selecione apenas os alunos que foram aprovados.

4) Salve o DataFrame que possui apenas os alunos aprovados em um arquivo csv chamado "alunos_aprovados.csv".

Extra: Ao conferir as notas dos alunos aprovados, notamos que algumas notas estavam incorretas. As alunas que tiraram nota 7.0, na verdade, tinham um ponto extra que não foi contabilizado. Sendo assim, substitua as notas 7.0 da base de dados por 8.0. Dica: pesquise pelo método replace.

In [12]:
dados.isnull().sum()
dados.fillna(0)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [13]:
ex_alunos = dados.query(' Nome in ("Alice", "Carlos")').index
dados.drop(ex_alunos, axis=0, inplace=True)
dados

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

In [14]:
dados.replace(7,8,inplace= True)

In [15]:
filtro = dados['Aprovado'] == True
alunos_aprovados = dados[filtro]

In [16]:
alunos_aprovados.to_csv('alunos_aprovados.csv', index = False)

In [17]:
pd.read_csv('alunos_aprovados.csv')

        Nome  Idade  Notas  Aprovado
0        Ary     20    7.5      True
1       Beto     21   10.0      True
2       Dara     21    8.0      True
3  Sthefanie     26    9.5      True
4      Mirla     25    9.0      True
5     Mylena     29    8.0      True
6      Nadia     34    8.0      True

1) Os alunos participaram de uma atividade extracurricular e ganharam pontos extras. Esses pontos extras correspondem a 40% da nota atual de cada um deles. Com base nisso, crie uma coluna chamada "Pontos_extras" que contenha os pontos extras de cada aluno, ou seja, 40% da nota atual deles.

2) Crie mais uma coluna, chamada "Notas_finais" que possua as notas de cada aluno somada com os pontos extras.

3) Como houve uma pontuação extra, alguns alunos que não tinham sido aprovados antes podem ter sido aprovados agora. Com base nisso, crie uma coluna chamada "Aprovado_final" com os seguintes valores:

True: caso o aluno esteja aprovado (nota final deve ser maior ou igual a 6);
False: caso o aluno esteja reprovado (nota final deve ser menor que 6).

4) Faça uma seleção e verifique quais alunos não tinham sido aprovados anteriormente, mas foram aprovados após a soma dos pontos extras.'

In [20]:
dados['Pontos_extras'] = dados['Notas']*0.4
dados.head()

    Nome  Idade  Notas  Aprovado  Pontos_extras
0    Ary     20    7.5      True            3.0
1    Ana     18    NaN     False            NaN
2  Cátia     27    2.5     False            1.0
3  Denis     18    5.0     False            2.0
4   Beto     21   10.0      True            4.0

In [21]:
dados['Notas_finais'] = (dados['Notas'] + dados['Pontos_extras']).apply(lambda x: 10 if x>=10 else x)

In [22]:
dados.head()

    Nome  Idade  Notas  Aprovado  Pontos_extras  Notas_finais
0    Ary     20    7.5      True            3.0          10.0
1    Ana     18    NaN     False            NaN           NaN
2  Cátia     27    2.5     False            1.0           3.5
3  Denis     18    5.0     False            2.0           7.0
4   Beto     21   10.0      True            4.0          10.0

In [47]:
dados['Aprovado_final'] = dados['Notas_finais'].apply(lambda x: True if x >= 6 else False)
dados.head()

    Nome  Idade  Notas  Aprovado  Pontos_extras  Notas_finais  Aprovado_final
0    Ary     20    7.5      True            3.0          10.0            True
1    Ana     18    NaN     False            NaN           NaN           False
2  Cátia     27    2.5     False            1.0           3.5           False
3  Denis     18    5.0     False            2.0           7.0            True
4   Beto     21   10.0      True            4.0          10.0            True

In [48]:
dados.query('Aprovado == False & Aprovado_final == True')

     Nome  Idade  Notas  Aprovado  Pontos_extras  Notas_finais  Aprovado_final
3   Denis     18    5.0     False            2.0           7.0            True
11   Igor     24    4.5     False            1.8           6.3            True

In [49]:
filtro_aprovados_final =  dados['Aprovado_final'] == True
aprovados_final = dados[filtro_aprovados_final]

In [50]:
aprovados_final.to_csv('alunos_aprovados.csv', index = False)